# -*- mode: ruby -*-
# vi: set ft=ruby :

load '../common/timestamp-appender.rb'

Vagrant.configure("2") do |config|
  config.vm.define "repo" do |repo|
    repo.vm.box = "codeyourinfra/repo"
    repo.vm.hostname = "repo"
    repo.vm.network "private_network", ip: "192.168.33.10"
  end

  (1..2).each do |i|
    config.vm.define "server#{i}" do |server|
      server.vm.box = "ubuntu/bionic64"
      server.vm.hostname = "server#{i}"
      server.vm.network "private_network", ip: "192.168.33.#{i+1}0"
    end
  end

  config.vm.provider "virtualbox" do |v|
    v.linked_clone = true if Gem::Version.new(Vagrant::VERSION) >= Gem::Version.new('1.8.0')
  end
end
