---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
  options:
    provision: false
lint:
  name: yamllint
platforms:
  - name: qa1
    box: ubuntu/bionic64
    interfaces:
      - network_name: private_network
        ip: 192.168.33.10
    groups:
      - qa
  - name: qa2
    box: ubuntu/bionic64
    interfaces:
      - network_name: private_network
        ip: 192.168.33.20
    groups:
      - qa
  - name: qa3
    box: ubuntu/bionic64
    interfaces:
      - network_name: private_network
        ip: 192.168.33.30
    groups:
      - qa
provisioner:
  name: ansible
  log: true
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  directory: ../tests
  lint:
    name: flake8
