---
language: python
python: "3.6"

addons:
  apt:
    packages:
    - python-pip

install:
  - pip install -r requirements.txt

script:
  - cd check_server_log_files && molecule test -s aws
  - cd ../get_metrics_for_alerting && molecule test -s aws
  - cd ../same_cfgfile_diff_content && molecule test -s docker

notifications:
  slack:
    secure: d6HN8M8LiaSmeYydgUNviGOzShnrRr3PSpwd+DYUOYpCSVOtyoiCsXWuIdMpo5dC3ZUgiiq2ThIbAMJ604j2ebA6o8nnkBEkHIOXd3hN1W6LrnAF4pgez5VdpBqru0YmDTxcuUCLotjhsJNHJy2GY+HtZBNMEc4tU/+lVbT9FjDutVJybjuJwRY2zUZWFJfw1pHmfDsN0MX6yeLQRBilwNFSviE6KuSU0t8ib1ZK5Y7hK0yBUdskBdLp8HTgWkH7xnZ9nYFfwydGEr9EvXfGGsCsN8WJ6yVD9iv2GMd0k6v4ZYCVJ4GnVqNK3qR1NLcnfRq+mIUHPl0qUwxrlBikKdfA+/Cygc3PH6bWrupuI8L/W9lavbEmsUJULXpW0TwhYq19e/mJUiSAESAisSsBLXPo2g4z29J1nuyOkfqcyHaz8Pzohr0k5HRYvLmWhqnxqDhMf/33uA9MxYzvjZYPcaGEuSmUHJTGOyBxaQaN0nt5pvEOON/fBwFr487fyeN4cIOjdfIZj+YWq/8Pn1pWyeRaZJ/swpvJHRsWS20RnmaCb2x2A7/Md60A4/xUmg0tTZd7lnF8gn+rFjgJ6Yzs5NFlUa2LrfXFxnOPUlagXf3Xv6DfUJqj5OWNYpKq8M1ek9c3F2TVNudY1zgbnAN4xYJvmZv8xGxtfPV7Aw28cFk=