# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "minimal/trusty64"
  config.vm.hostname = "jenkins.local"
  config.vm.network "private_network", ip: "192.168.33.10"
    #jenkins.vm.provision "ansible" do |ansible|
    #  ansible.playbook = "playbook-jenkins.yml"
    #end
end
