---
- hosts: monitor
  become: true
  roles:
    - role: monitor_cron
      vars:
        playbooks:
          - playbook-get-metrics.yml
  tasks:
    - name: Install influxdb Python package
      pip:
        name: influxdb
    - name: Create the InfluxDB database
      influxdb_database:
        database_name: monitor
    - name: Create the Grafana datasource
      uri:
        url: http://localhost:3000/api/datasources
        method: POST
        user: admin
        password: admin
        force_basic_auth: true
        body: "{{lookup('file','monitor-datasource.json')}}"
        body_format: json
      register: response
      changed_when: response.status == 200
      failed_when: response.status != 200 and response.json.message != "Data source with same name already exists"
    - name: Get the alert notifications
      uri:
        url: http://localhost:3000/api/alert-notifications
        method: GET
        user: admin
        password: admin
        force_basic_auth: true
      register: alert_notifications
    - name: Create the Slack notification channel
      uri:
        url: http://localhost:3000/api/alert-notifications
        method: POST
        user: admin
        password: admin
        force_basic_auth: true
        body: "{{lookup('file','slack-notification-channel.json')}}"
        body_format: json
      when: alert_notifications.json|json_query("[?name=='Slack notification channel']")|length == 0
      register: response
      changed_when: response.status == 200
    - name: Create the Grafana dashboard
      uri:
        url: http://localhost:3000/api/dashboards/db
        method: POST
        user: admin
        password: admin
        force_basic_auth: true
        body: "{{lookup('file','used_mem_pct-dashboard.json')}}"
        body_format: json
      register: response
      changed_when: response.status == 200
      failed_when: response.status != 200 and response.json.message != "A dashboard with the same name in the folder already exists"
