---
dependency:
  name: galaxy
driver:
  name: ec2
lint:
  name: yamllint
platforms:
  - name: monitor
    region: eu-west-2
    image_owner: 334305766942
    image_name: codeyourinfra/monitor
    instance_type: t2.micro
    vpc_subnet_id: subnet-1cb17175
  - name: server1
    region: eu-west-2
    image_owner: 099720109477
    image_name: ubuntu/images/hvm-ssd/ubuntu-bionic-18.04-amd64-server-*
    instance_type: t2.micro
    vpc_subnet_id: subnet-1cb17175
    groups:
      - servers
  - name: server2
    region: eu-west-2
    image_owner: 099720109477
    image_name: ubuntu/images/hvm-ssd/ubuntu-bionic-18.04-amd64-server-*
    instance_type: t2.micro
    vpc_subnet_id: subnet-1cb17175
    groups:
      - servers
provisioner:
  name: ansible
  log: true
  lint:
    name: ansible-lint
  env:
    ANSIBLE_ROLES_PATH: ../../roles/
  inventory:
    group_vars:
      all:
        ansible_python_interpreter: python3
scenario:
  name: aws
  test_sequence:
    - lint
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - destroy
verifier:
  name: testinfra
  directory: ../tests
  lint:
    name: flake8
