---
- name: Converge
  become: true
  hosts: monitor
  roles:
    - role: monitor_inventory
      vars:
        monitored_servers:
          - host: "{{ hostvars['server1']['ansible_host'] }}"
            user: ubuntu
            private_key: "{{ hostvars['server1']['ansible_private_key_file'] }}"
          - host: "{{ hostvars['server2']['ansible_host'] }}"
            user: ubuntu
            private_key: "{{ hostvars['server2']['ansible_private_key_file'] }}"
