# -*- mode: ruby -*-
# vi: set ft=ruby :

def get_region()
  aws_config_file = File.expand_path('~/.aws/config')
  if File.file?(aws_config_file)
    region_line = File.foreach(aws_config_file).detect { |line| line.start_with?('region') }
    region_line.split('=')[-1].strip if region_line
  end
end
aws_region = ENV['AWS_REGION'] || ENV['EC2_REGION'] || get_region() || "sa-east-1"
if !Dir.exists?(aws_region)
  puts 'The directory ' + aws_region + ' does not exist.'
  abort
end
security_group  = JSON.parse(File.read(File.join(aws_region, "security-group.json")))
subnet = JSON.parse(File.read(File.join(aws_region, "subnet.json")))
ubuntu_ami = JSON.parse(File.read(File.join(aws_region, "ubuntu-ami.json")))

Vagrant.configure("2") do |config|
  config.vm.box = "dummy"
  config.vm.box_url = "https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box"
  config.vm.synced_folder ".", "/vagrant", disabled: true

  (1..3).each do |i|
    config.vm.define "test#{i}" do |test|
      test.vm.provider "aws" do |aws, override|
        aws.region = aws_region
        aws.ami = ubuntu_ami['image_id']
        aws.instance_type = "t2.micro"
        aws.keypair_name = "codeyourinfra-aws-key"
        aws.security_groups = security_group['group_id']
        aws.subnet_id = subnet['id']
        aws.tags = {"Name" => "test#{i}"}
        override.ssh.username = "ubuntu"
        override.ssh.private_key_path = File.join(aws_region, "codeyourinfra-aws-key.pem")
        override.nfs.functional = false
      end
    end
  end
end
