# -*- mode: ruby -*-
# vi: set ft=ruby :

security_group  = (JSON.parse(File.read("vagrant-security-group.json")))
network_interface = (JSON.parse(File.read("network-interface.json")))
ubuntu_ami = (JSON.parse(File.read("ubuntu-trusty-14.04-amd64-server.json")))

Vagrant.configure("2") do |config|
  config.vm.box = "dummy"
  config.vm.synced_folder ".", "/vagrant", disabled: true

  (1..3).each do |i|
    config.vm.define "test#{i}" do |test|
      test.vm.provider "aws" do |aws, override|
        aws.region = "sa-east-1"
        aws.ami = ubuntu_ami['ami_id']
        aws.instance_type = "t2.micro"
        aws.keypair_name = "codeyourinfra-aws-key"
        aws.security_groups = security_group['group_id']
        aws.subnet_id = network_interface['subnet_id']
        aws.tags = {"Name" => "test#{i}"}
        override.ssh.username = "ubuntu"
        override.ssh.private_key_path = "codeyourinfra-aws-key.pem"
        override.nfs.functional = false
      end
    end
  end
end
