# -*- mode: ruby -*-
# vi: set ft=ruby :

load 'aws-parameters.rb'
region, security_group, subnet, ami, private_key = get_parameters()

Vagrant.configure("2") do |config|
  config.vm.box = "dummy"
  config.vm.box_url = "https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box"
  config.vm.synced_folder ".", "/vagrant", disabled: true

  (1..3).each do |i|
    config.vm.define "test#{i}" do |test|
      test.vm.provider "aws" do |aws, override|
        aws.region = region
        aws.ami = ami
        aws.instance_type = "t2.micro"
        aws.keypair_name = "codeyourinfra-aws-key"
        aws.security_groups = security_group
        aws.subnet_id = subnet
        aws.tags = {"Name" => "test#{i}"}
        override.ssh.username = "ubuntu"
        override.ssh.private_key_path = private_key
        override.nfs.functional = false
      end
    end
  end
end
