# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "minimal/trusty64"

  config.vm.define "qa1" do |qa1|
    qa1.vm.hostname = "qa1.local"
    qa1.vm.network "private_network", ip: "192.168.33.10"
  end

  config.vm.define "qa2" do |qa2|
    qa2.vm.hostname = "qa2.local"
    qa2.vm.network "private_network", ip: "192.168.33.20"
  end

  config.vm.define "qa3" do |qa3|
    qa3.vm.hostname = "qa3.local"
    qa3.vm.network "private_network", ip: "192.168.33.30"
  end
end
