---
dependency:
  name: galaxy
driver:
  name: ec2
lint:
  name: yamllint
platforms:
  - name: jenkins
    region: eu-west-2
    image_owner: 334305766942
    image_name: codeyourinfra/jenkins
    instance_type: t2.micro
    vpc_subnet_id: subnet-1cb17175
provisioner:
  name: ansible
  log: true
  lint:
    name: ansible-lint
scenario:
  name: aws
  test_sequence:
    - lint
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - destroy
verifier:
  name: testinfra
  directory: ../tests
  lint:
    name: flake8
