---
- name: Set parameters
  set_fact:
    param_host: "{{ item.host if item is defined else host | default(omit) }}"
    param_user: "{{ item.user if item is defined else user | default(omit) }}"
    param_password: "{{ item.password if item is defined and item.password is defined else password | default(omit) }}"
    param_private_key: "{{ item.private_key if item is defined and item.private_key is defined else private_key | default(omit) }}"

- block:
    - name: Install sshpass
      apt:
        name: sshpass
        update_cache: true
    - name: Add the server into the monitored_servers group
      lineinfile:
        path: /etc/ansible/hosts
        insertafter: "^\\[monitored_servers\\]$"
        line: "{{ param_host }} ansible_user={{ param_user }} ansible_ssh_pass={{ param_password }}"
  when: param_host is defined and param_user is defined and param_password is defined

- block:
    - name: Copy the SSH user private key
      copy:
        src: "{{ param_private_key }}"
        dest: "/etc/ansible/{{ param_host }}.private_key"
        mode: 0400
    - name: Add the server into the monitored_servers group
      lineinfile:
        path: /etc/ansible/hosts
        insertafter: "^\\[monitored_servers\\]$"
        line: "{{ param_host }} ansible_user={{ param_user }} ansible_ssh_private_key_file=/etc/ansible/{{ param_host }}.private_key"
  when: param_host is defined and param_user is defined and param_private_key is defined
