---
- name: Create the Ansible directory if it doesn't exist
  file:
    path: /etc/ansible
    state: directory
- name: Copy the Ansible inventory
  copy:
    src: monitored_hosts
    dest: /etc/ansible/hosts
    force: false
- name: Disable SSH key host checking
  ini_file:
    path: /etc/ansible/ansible.cfg
    section: defaults
    option: host_key_checking
    value: false

- name: Check if must add a single server
  set_fact:
    single_server: "{{ host is defined and user is defined and (password is defined or private_key is defined) }}"
- name: Add server to monitor inventory
  include_tasks: add-server.yml
  when: single_server
- name: Add server(s) to monitor inventory
  include_tasks: add-server.yml
  loop: "{{ monitored_servers }}"
  no_log: true
  when: monitored_servers is defined and not single_server
