---
- name: Set the configuration file content
  lineinfile:
    path: "{{ cfgfile_path }}"
    create: true
    regexp: "^{{ item.key }}=.*$"
    line: "{{ item.key }}={{ item.value }}"
  loop: "{{ content[inventory_hostname] | dict2items }}"
